/**
 * @file Docs_TrackManager.cs
 * @brief Documentation entry for the Track Management subsystem.
 *
 * @defgroup track_mng Track Manager
 * @ingroup systems
 * @brief Race flow control, checkpoint progression, restart/respawn handling, and player car spawning.
 *
 * @details
 * The Track Manager is implemented by ::TrackManager, a MonoBehaviour placed in the race scene.
 * It coordinates the runtime race lifecycle: spawning/restarting the player car, checkpoint
 * activation, lap progression, point-to-point completion, circuit completion, respawn handling,
 * and camera target assignment.
 *
 * The subsystem exposes race-progress properties such as the current lap, next required checkpoint,
 * finish state, and respawn countdown. Race timing itself is coordinated through ::RaceTimeManager.
 *
 * Contents:
 * - @ref track_mng_overview
 * - @ref track_mng_inspector
 * - @ref track_mng_lifecycle
 * - @ref track_mng_checkpoints
 * - @ref track_mng_respawn
 * - @ref track_mng_usage
 * - @ref track_mng_api
 * - @ref track_mng_integration
 * - @ref track_mng_troubleshooting
 * - @ref track_mng_versions
 *
 * ----------------------------------------------------------------------
 * @section track_mng_overview Overview
 *
 * Responsibilities:
 * - Spawning the player car at a designated spawn transform, with a fallback to the TrackManager transform.
 * - Wiring the ::FollowCamera target to the spawned car and syncing it after respawns.
 * - Managing race flow for circuit and point-to-point tracks.
 * - Tracking checkpoint order and enabling only the next required checkpoint.
 * - Handling player-initiated respawn and full restart actions through the Unity Input System.
 * - Starting and ending race timing through ::RaceTimeManager.
 * - Clearing stale selected level data when a scene-defined track is started without a generated-track placer.
 *
 * Dependencies:
 * - UnityEngine.InputSystem for InputActionProperty-based respawn and restart actions.
 * - ::CheckPointManager for checkpoint registration, activation, deactivation, and lookup.
 * - ::CheckPointListener components placed in the scene or generated by the track builder.
 * - ::RaceTrackPlacer for generated-track setup.
 * - ::FollowCamera for target assignment and SyncCamera() calls.
 * - ::RaceTimeManager for race start, lap pass, and race end timing.
 * - ::GameDataManager for clearing selected level-map state when using scene-defined tracks.
 *
 * Threading:
 * - Unity main thread only.
 * - Uses MonoBehaviour lifecycle methods, input callbacks, Rigidbody state, and coroutines.
 *
 * Invariants:
 * - Checkpoints are visited in configured order.
 * - Only the next expected checkpoint is active.
 * - In circuit mode, checkpoint 0 acts as the lap gate.
 * - In point-to-point mode, the final checkpoint ends the race.
 * - Respawn places the car at the last valid checkpoint claim, including position, rotation, and velocities.
 *
 * ----------------------------------------------------------------------
 * @section track_mng_inspector Inspector (TrackManager)
 *
 * Spawn:
 * - CarSpawn (Transform): preferred spawn transform for the player car.
 *   If null, the TrackManager transform is used as a fallback.
 *
 * Input Settings:
 * - respawnLastCheckPoint (InputActionProperty): input action used to respawn at the previous checkpoint.
 * - restartRace (InputActionProperty): input action used to restart the whole race.
 * - defaultBindings (bool): if true, default actions and bindings are created in OnValidate().
 *
 * Car Prefab Reference:
 * - carPrefab (GameObject): player car prefab instantiated when the race starts or restarts.
 * - carSpawnVerticalOffset (float): vertical offset applied when spawning the car.
 * - carSpawnHorizontalOffset (float): forward/backward offset applied relative to the spawn rotation.
 *
 * Track Settings:
 * - levelMap (levelMap): runtime level map used when the race is started from generated or saved track data.
 * - isCircuit (bool): true for lap-based circuit races; false for point-to-point races.
 * - laps (int, ShowIf(isCircuit)): number of laps required to finish a circuit race.
 *
 * Respawn Delay:
 * - respawnDelay (float, 0..5): real-time freeze duration used during respawn.
 *
 * Runtime Properties (read-only):
 * - CurrentLap (int): current lap number.
 * - TotalLaps (int): configured lap count for circuit races.
 * - CurrentCheckPointIndex (int): index of the next checkpoint that must be claimed.
 * - IsRaceFinished (bool): whether the race has ended.
 * - RespawnTimer (float): visible countdown value during respawn or restart countdowns.
 *
 * ----------------------------------------------------------------------
 * @section track_mng_lifecycle Lifecycle
 *
 * OnValidate:
 * - Optionally creates default input actions and bindings.
 * - Default respawn bindings: Backspace, Triangle, ButtonNorth.
 * - Default restart bindings: Delete, Start.
 *
 * OnEnable:
 * - Enables respawn and restart actions.
 * - Subscribes performed callbacks for respawn and restart input.
 *
 * OnDisable:
 * - Unsubscribes input callbacks.
 * - Disables respawn and restart actions.
 *
 * Start:
 * - If a ::RaceTrackPlacer exists, generated-track setup is expected and this method returns early.
 * - Otherwise, clears the currently selected level map through ::GameDataManager.
 * - Clears and auto-collects scene checkpoints through ::CheckPointManager.
 * - Starts the race using the scene-defined checkpoint layout.
 *
 * FixedUpdate:
 * - Starts the respawn coroutine when a respawn request is pending.
 *
 * Restart flow:
 * - Restart input starts or restarts the restart countdown coroutine.
 * - The restart coroutine replaces the car, resets race state, pauses time briefly, and then resumes gameplay.
 *
 * ----------------------------------------------------------------------
 * @section track_mng_checkpoints Checkpoints & Laps
 *
 * - Checkpoints are owned and activated through ::CheckPointManager.
 * - ::TrackManager::CheckPointTaken() is registered as the checkpoint listener callback.
 * - Only the next expected checkpoint is active.
 * - When the active checkpoint is claimed, the manager advances the checkpoint index and activates the next one.
 *
 * Circuit mode:
 * - Checkpoint 0 acts as the lap gate.
 * - The first pass initializes lap progress.
 * - Later passes call ::RaceTimeManager::LapPassed().
 * - When the configured lap count has been reached and checkpoint 0 is claimed again, the race finishes.
 *
 * Point-to-point mode:
 * - The race finishes when the final checkpoint is claimed.
 * - On finish, all checkpoints are deactivated and ::RaceTimeManager::RaceEnd() is called.
 *
 * ----------------------------------------------------------------------
 * @section track_mng_respawn Respawn & Restart
 *
 * Respawn:
 * - If the race is finished, respawn input starts a full restart countdown.
 * - If the player is before the first checkpoint, respawn becomes a full restart.
 * - In circuit mode, when the checkpoint index has wrapped to zero after at least one lap,
 *   respawn targets the final checkpoint from the previous lap.
 * - Otherwise, respawn targets the previous checkpoint.
 *
 * Respawn mechanics:
 * - The pending respawn flag is consumed in FixedUpdate.
 * - The car Rigidbody interpolation state is temporarily adjusted for a clean teleport.
 * - The car is moved to the saved checkpoint pose.
 * - Linear and angular velocities saved by the checkpoint are restored.
 * - Physics transforms are synchronized.
 * - The follow camera is synchronized.
 * - Gameplay is paused for a short real-time countdown using Time.timeScale = 0.
 *
 * Restart:
 * - Destroys the existing car instance if one exists.
 * - Spawns a new car near CarSpawn, or near the TrackManager transform as fallback.
 * - Tags the spawned car as Player.
 * - Assigns the spawned car as the follow-camera target.
 * - Resets lap, checkpoint, and finish state.
 * - Calls ::RaceTimeManager::RaceStart().
 * - Deactivates all checkpoints and activates checkpoint 0.
 * - Runs a fixed restart countdown while gameplay time is paused.
 *
 * ----------------------------------------------------------------------
 * @section track_mng_usage Usage
 *
 * Scene-defined track:
 * - Place a TrackManager in the race scene.
 * - Add CheckPointListener objects to the scene.
 * - Ensure CheckPointManager can auto-collect the checkpoints in the intended order.
 * - Optionally assign CarSpawn; otherwise the TrackManager transform is used.
 * - Assign the player car prefab.
 * - Ensure the main camera has a ::FollowCamera component.
 * - Start the scene. If no ::RaceTrackPlacer exists, TrackManager starts from the scene-defined checkpoints.
 *
 * Generated or saved track:
 * - A ::RaceTrackPlacer is responsible for generated-track setup.
 * - When a RaceTrackPlacer exists, TrackManager.Start() returns early.
 * - The generated-track flow should provide the track layout and call ::TrackManager::StartRace(levelMap).
 *
 * Custom inputs:
 * - Disable defaultBindings.
 * - Assign respawnLastCheckPoint and restartRace through an Input Actions asset.
 *
 * ----------------------------------------------------------------------
 * @section track_mng_api Public API Reference
 *
 * Race control:
 * - void StartRace(levelMap lvlMap): configures race settings from an optional level map,
 *   wires checkpoint listeners, and starts the restart countdown.
 * - void CheckPointTaken(): advances checkpoint and lap progression, records lap transitions,
 *   and finishes the race when the required final condition is met.
 *
 * Runtime progress:
 * - int CurrentLap: current lap number.
 * - int TotalLaps: required lap count for circuit races.
 * - int CurrentCheckPointIndex: next checkpoint that must be claimed.
 * - bool IsRaceFinished: whether the race has ended.
 * - float RespawnTimer: visible countdown value during restart or respawn.
 *
 * Internal restart and respawn helpers:
 * - Respawn(): selects the previous checkpoint or starts a full restart according to race state.
 * - RespawnCar(int index): restores the car pose and velocities stored by a checkpoint.
 * - Restart(): replaces the car, resets progress, starts timing, and re-arms checkpoints.
 * - RestartCoroutine(): performs restart and pauses gameplay during the restart countdown.
 * - RespawnDelayCoroutine(float delay): performs respawn teleport and pauses gameplay during the respawn countdown.
 *
 * ----------------------------------------------------------------------
 * @section track_mng_integration Integration Notes
 *
 * - ::RaceTrackPlacer handles generated-track setup. When it exists, TrackManager.Start() returns early.
 * - ::CheckPointManager owns the runtime checkpoint list and checkpoint activation/deactivation operations.
 * - ::CheckPointListener captures respawn position, rotation, linear velocity, and angular velocity.
 * - ::TrackManager consumes saved checkpoint data during respawn.
 * - ::FollowCamera must exist on the main camera and support target assignment plus SyncCamera().
 * - ::RaceTimeManager is responsible for race start, lap pass, and race end timing.
 * - ::GameDataManager::UnselectLevelMap() is used when starting a scene-defined race so stale selected
 *   level data does not remain active.
 *
 * ----------------------------------------------------------------------
 * @section track_mng_troubleshooting Troubleshooting
 *
 * Car not spawning:
 * - Ensure carPrefab is assigned.
 * - Verify CarSpawn exists or that the TrackManager transform is a sensible fallback spawn point.
 * - Check that the spawned prefab has a Rigidbody.
 *
 * Checkpoints not advancing:
 * - Confirm checkpoints were registered in ::CheckPointManager.
 * - Confirm only the next required checkpoint is active.
 * - Ensure the player car is tagged "Player".
 * - Verify each checkpoint listener calls ::TrackManager::CheckPointTaken().
 *
 * Respawn puts the car in the wrong place:
 * - Verify each ::CheckPointListener captures the claim position and rotation correctly.
 * - Check that checkpoint ordering matches the intended driving order.
 * - Confirm saved linear and angular velocities are valid.
 *
 * Restart behaves like a scene reset but old selected level data remains:
 * - For scene-defined races, TrackManager.Start() clears the selected level map through ::GameDataManager.
 * - For generated-track races, setup should be handled by ::RaceTrackPlacer.
 *
 * Timer not moving:
 * - Race time is paused during respawn and restart countdowns with Time.timeScale = 0.
 * - Ensure the countdown reaches zero and gameplay time is restored.
 *
 * Camera not following after restart or respawn:
 * - Ensure Camera.main exists.
 * - Ensure the main camera has a ::FollowCamera component.
 * - Check that the spawned car is assigned as the camera target after restart.
 *
 * ----------------------------------------------------------------------
 * @section track_mng_versions Version History
 *
 * - v1.2: Scene-defined race startup clears selected level-map state and auto-collects checkpoints
 *         when no RaceTrackPlacer is present.
 * - v1.1: Respawn freeze timer and countdown-ready timer added; circuit and point-to-point flows unified.
 * - v1.0: Basic checkpoints, lap counting, restart, respawn, car spawning, and race flow.
 */